controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Head Controller
    head_controller:
      type: effort_controllers/JointTrajectoryController

    # Left Arm Controller
    left_arm_controller:
      type: effort_controllers/JointTrajectoryController

    # Right Arm Controller  
    right_arm_controller:
      type: effort_controllers/JointTrajectoryController

    # Left Gripper Controller
    left_gripper_controller:
      type: effort_controllers/JointTrajectoryController

    # Right Gripper Controller
    right_gripper_controller:
      type: effort_controllers/JointTrajectoryController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - head_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_gripper_joint_1
      - left_gripper_joint_2
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_gripper_joint_1
      - right_gripper_joint_2

# Head Controller Configuration
head_controller:
  ros__parameters:
    joints:
      - head_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      head_joint:
        trajectory: 0.05
        goal: 0.03

# Left Arm Controller Configuration
left_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0
      left_shoulder_pan_joint:
        trajectory: 0.1
        goal: 0.05
      left_shoulder_lift_joint:
        trajectory: 0.1
        goal: 0.05
      left_elbow_joint:
        trajectory: 0.1
        goal: 0.05
      left_wrist_1_joint:
        trajectory: 0.1
        goal: 0.05
      left_wrist_2_joint:
        trajectory: 0.1
        goal: 0.05

# Right Arm Controller Configuration
right_arm_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0
      right_shoulder_pan_joint:
        trajectory: 0.1
        goal: 0.05
      right_shoulder_lift_joint:
        trajectory: 0.1
        goal: 0.05
      right_elbow_joint:
        trajectory: 0.1
        goal: 0.05
      right_wrist_1_joint:
        trajectory: 0.1
        goal: 0.05
      right_wrist_2_joint:
        trajectory: 0.1
        goal: 0.05

# Left Gripper Controller Configuration
left_gripper_controller:
  ros__parameters:
    joints:
      - left_gripper_joint_1
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      left_gripper_joint_1:
        trajectory: 0.02
        goal: 0.01

# Right Gripper Controller Configuration
right_gripper_controller:
  ros__parameters:
    joints:
      - right_gripper_joint_1
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      right_gripper_joint_1:
        trajectory: 0.02
        goal: 0.01